services:
  fiap-adj8-feedback-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap-adj8-feedback-app
    ports:
      - "8081:8080"
      - "5006:5005"
    environment:
      TEST: "TEST"
    depends_on:
      fiap-adj8-feedback-app-db:
        condition: service_healthy

  fiap-adj8-feedback-app-db:
    image: postgres:16-alpine
    container_name: feedback_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: feedback_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d feedback_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: { }
